The first block of code prints 3. The second one throws and error because
x is only definded inside scope and cannot be accessed outside.